
package exercicios.exe01.views;

import exercicios.exe01.entities.Conversor5;

public class janelaConversor5 extends javax.swing.JFrame {
    private Conversor5 c = new Conversor5();
    /**
     * Creates new form janelaConversor5
     */
    public janelaConversor5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cxC = new javax.swing.JTextField();
        cxF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cxK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cxCtoF = new javax.swing.JLabel();
        cxCtoK = new javax.swing.JLabel();
        cxFtoC = new javax.swing.JLabel();
        cxFtoK = new javax.swing.JLabel();
        cxKtoF = new javax.swing.JLabel();
        cxKtoC = new javax.swing.JLabel();
        btK = new javax.swing.JButton();
        btC = new javax.swing.JButton();
        btF = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor");

        jLabel1.setText("Celsius");

        cxC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCActionPerformed(evt);
            }
        });

        cxF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxFActionPerformed(evt);
            }
        });

        jLabel2.setText("Fahrenheit");

        cxK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxKActionPerformed(evt);
            }
        });

        jLabel3.setText("Kelvin");

        cxCtoF.setText(".....F");

        cxCtoK.setText(".....K");

        cxFtoC.setText(".....ºC");

        cxFtoK.setText(".....K");

        cxKtoF.setText(".....F");

        cxKtoC.setText(".....ºC");

        btK.setText("OK");
        btK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKActionPerformed(evt);
            }
        });

        btC.setText("OK");
        btC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCActionPerformed(evt);
            }
        });

        btF.setText("OK");
        btF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setText("Conversor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(cxC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(cxCtoF)
                        .addGap(46, 46, 46)
                        .addComponent(cxCtoK))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(cxF, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(cxFtoC)
                        .addGap(44, 44, 44)
                        .addComponent(cxFtoK))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(cxK, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(cxKtoC)
                        .addGap(44, 44, 44)
                        .addComponent(cxKtoF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btF, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btK, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1))
                            .addComponent(cxC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cxCtoF)
                                    .addComponent(cxCtoK))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel2))
                                .addComponent(cxF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(cxFtoC))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(cxFtoK))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3))
                            .addComponent(cxK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(cxKtoC))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cxKtoF)
                                    .addComponent(btK, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(438, 245));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cxCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCActionPerformed

    private void cxFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxFActionPerformed

    private void cxKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxKActionPerformed

    private void btKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKActionPerformed
        cxKtoC.setText(c.kelvinToCelsius(Double.parseDouble(cxK.getText())) +"ºC");
        cxKtoF.setText(c.kelvinToFahrenheit(Double.parseDouble(cxK.getText())) +"F");
    }//GEN-LAST:event_btKActionPerformed

    private void btCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCActionPerformed
        cxCtoF.setText(c.celsiusToFahrenheit(Double.parseDouble(cxC.getText())) +"F");
        cxCtoK.setText(c.celsiusToKelvin(Double.parseDouble(cxC.getText())) +"K");

    }//GEN-LAST:event_btCActionPerformed

    private void btFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFActionPerformed
        cxFtoC.setText(c.fahrenheitToCelsius(Double.parseDouble(cxF.getText())) +"ºC");        
        cxFtoK.setText(c.fahrenheitToKelvin(Double.parseDouble(cxF.getText())) +"K");
    }//GEN-LAST:event_btFActionPerformed

  
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janelaConversor5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btC;
    private javax.swing.JButton btF;
    private javax.swing.JButton btK;
    private javax.swing.JTextField cxC;
    private javax.swing.JLabel cxCtoF;
    private javax.swing.JLabel cxCtoK;
    private javax.swing.JTextField cxF;
    private javax.swing.JLabel cxFtoC;
    private javax.swing.JLabel cxFtoK;
    private javax.swing.JTextField cxK;
    private javax.swing.JLabel cxKtoC;
    private javax.swing.JLabel cxKtoF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
